---
title: "salmon_merge_quant"
author: "Carlos Eduardo Madureira Trufen"
date: "June 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r }
library(readr)
```

# Read in salmon count tables
```{r }
quant = list()
quant[[1]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S01B01_salmon_transcripts_quant/quant.sf")
quant[[2]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S01B02_salmon_transcripts_quant/quant.sf")
quant[[3]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S01B03_salmon_transcripts_quant/quant.sf")
quant[[4]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S01B04_salmon_transcripts_quant/quant.sf")
quant[[5]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S02B01_salmon_transcripts_quant/quant.sf")
quant[[6]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S02B02_salmon_transcripts_quant/quant.sf")
quant[[7]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S02B03_salmon_transcripts_quant/quant.sf")
quant[[8]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S02B04_salmon_transcripts_quant/quant.sf")
quant[[9]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S03B01_salmon_transcripts_quant/quant.sf")
quant[[10]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S03B02_salmon_transcripts_quant/quant.sf")
quant[[11]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S03B03_salmon_transcripts_quant/quant.sf")
quant[[12]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S03B04_salmon_transcripts_quant/quant.sf")
quant[[13]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S04B01_salmon_transcripts_quant/quant.sf")
quant[[14]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S04B02_salmon_transcripts_quant/quant.sf")
quant[[15]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S04B03_salmon_transcripts_quant/quant.sf")
quant[[16]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S04B04_salmon_transcripts_quant/quant.sf")
quant[[17]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S05B01_salmon_transcripts_quant/quant.sf")
quant[[18]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S05B02_salmon_transcripts_quant/quant.sf")
quant[[19]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S05B03_salmon_transcripts_quant/quant.sf")
quant[[20]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S05B04_salmon_transcripts_quant/quant.sf")
quant[[21]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S06B01_salmon_transcripts_quant/quant.sf")
quant[[22]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S06B02_salmon_transcripts_quant/quant.sf")
quant[[23]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S06B03_salmon_transcripts_quant/quant.sf")
quant[[24]] <- read.delim("~/bioinformatics/Hib/salmon/Hib_S06B04_salmon_transcripts_quant/quant.sf")

quant = lapply(1:length(quant), function(i){data.frame(Name = quant[[i]]$Name, NumReads = quant[[i]]$NumReads)})
```

# Merge tables by column "transcript"
```{r }
library(dplyr)
merged_data = full_join(quant[[1]], quant[[2]], by="Name")
for (i in 3:length(quant)){merged_data = full_join(merged_data, quant[[i]], by="Name") }
colnames(merged_data) = c("transcript", "S01B01", "S01B02", "S01B03", "S01B04", "S02B01", "S02B02", "S02B03", "S02B04", "S03B01", "S03B02", "S03B03", "S03B04", "S04B01", "S04B02", "S04B03", "S04B04", "S05B01", "S05B02", "S05B03", "S05B04", "S06B01", "S06B02", "S06B03", "S06B04")
rownames(merged_data) = merged_data$transcript
merged_data = merged_data[,-1]
merged_data = floor(merged_data)
merged_data = cbind(rownames(merged_data), merged_data)
colnames(merged_data) = c("transcript", "S01B01", "S01B02", "S01B03", "S01B04", "S02B01", "S02B02", "S02B03", "S02B04", "S03B01", "S03B02", "S03B03", "S03B04", "S04B01", "S04B02", "S04B03", "S04B04", "S05B01", "S05B02", "S05B03", "S05B04", "S06B01", "S06B02", "S06B03", "S06B04")
```

# save matrix
```{r }
write.table(merged_data, "~/Dropbox/Hib_Data/unaligned_spades_salmon_counts_matrix.tsv", sep ="\t", col.names = TRUE, row.names = FALSE)
```

```{r }
unaligned_spades_salmon_counts = read.delim("~/Dropbox/Hib_Data/unaligned_spades_salmon_counts_matrix.tsv", header=TRUE, row.names=1)
```










# Read in salmon count tables
```{r }
fi<-list.files("~/Dropbox/Hib_Data/salmon/counts",full.names=T)
dat<-lapply(fi,read.csv, sep="\t")
```

# Merge tables by column "transcript"
```{r }
merged_data = full_join(dat[[1]], dat[[2]], by="transcript")
for (i in 3:length(dat)){merged_data = full_join(merged_data, dat[[i]], by="transcript") }
colnames(merged_data) = c("transcript", "S01B01", "S01B02", "S01B03", "S01B04", "S02B01", "S02B02", "S02B03", "S02B04", "S03B01", "S03B02", "S03B03", "S03B04", "S04B01", "S04B02", "S04B03", "S04B04", "S05B01", "S05B02", "S05B03", "S05B04", "S06B01", "S06B02", "S06B03", "S06B04")
rownames(merged_data) = merged_data$transcript
merged_data = merged_data[,-1]
merged_data = floor(merged_data)
merged_data = cbind(rownames(merged_data), merged_data)
colnames(merged_data) = c("transcript", "S01B01", "S01B02", "S01B03", "S01B04", "S02B01", "S02B02", "S02B03", "S02B04", "S03B01", "S03B02", "S03B03", "S03B04", "S04B01", "S04B02", "S04B03", "S04B04", "S05B01", "S05B02", "S05B03", "S05B04", "S06B01", "S06B02", "S06B03", "S06B04")
```

# save matrix
```{r }
write.table(merged_data, "~/Dropbox/Hib_Data/unaligned_spades_salmon_counts_matrix.tsv", sep ="\t", col.names = TRUE, row.names = FALSE)
```

```{r }
unaligned_spades_salmon_counts = read.delim("~/Dropbox/Hib_Data/unaligned_spades_salmon_counts_matrix.tsv", header=TRUE, row.names=1)
```

```{r }

```

```{r }

```

```{r }

```

```{r }

```

```{r }

```


